# Backbone
backbone: resnet50

# Transfer loss related
transfer_loss_weight: 0.5
transfer_loss: mmd

# Optimizer related
lr: 0.003
weight_decay: 0.00005
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
momentum: 0.9